import { getAuthoritativeConversionMilestones } from "../dashboard/conversion-funnel";
import { parseConfirmedFacts } from "./facts";
import type { Acquisition, EvidenceCase } from "./domain";
import type { FinancialTruthEvent } from "../profitability/financial-truth";

export type CohortActivity = { id:string;leadId:string;kind:string;occurredAt:Date;description:string|null;metadata:Record<string,unknown> };
const priority=(kind:string)=>kind==="lead_created"?0:kind==="lead_attribution_updated"?1:kind==="caller_assigned"?2:kind==="caller_feedback"?3:4;
const empty=():Acquisition=>({source:null,campaign:null,ad:null,creative:null,acquisitionAngle:null});
function acquisition(metadata:Record<string,unknown>, prior:Acquisition){const source=metadata.after&&typeof metadata.after==="object"?metadata.after as Record<string,unknown>:metadata;const read=(key:keyof Acquisition)=>typeof source[key]==="string"?source[key] as string:source[key]===null?null:prior[key];return {source:read("source"),campaign:read("campaign"),ad:read("ad"),creative:read("creative"),acquisitionAngle:read("acquisitionAngle")};}
export function buildAsOfCases(input:{leads:readonly {id:string;type?:string;createdAt:Date}[];activities:readonly CohortActivity[];financial:readonly (FinancialTruthEvent&{leadId:string})[];asOf:Date}){
 const byLead=new Map<string,CohortActivity[]>();for(const event of input.activities.filter(x=>x.occurredAt<=input.asOf).sort((a,b)=>a.occurredAt.getTime()-b.occurredAt.getTime()||priority(a.kind)-priority(b.kind)||a.id.localeCompare(b.id))){const rows=byLead.get(event.leadId)??[];rows.push(event);byLead.set(event.leadId,rows);}
 return input.leads.filter(lead=>lead.createdAt<=input.asOf).map((lead):EvidenceCase=>{let attribution=empty();let assignmentAt=lead.createdAt;let questions:{questionKey:string;answer:string}[]=[];const events=byLead.get(lead.id)??[];const saleMilestones=events.flatMap(event=>getAuthoritativeConversionMilestones([event]).filter(x=>x.kind==="sale"));const outcomeCutoff=saleMilestones.sort((a,b)=>a.occurredAt.getTime()-b.occurredAt.getTime())[0]?.occurredAt??input.asOf;for(const event of events){if(event.kind==="lead_created"||event.kind==="lead_attribution_updated")attribution=acquisition(event.metadata,attribution);if(event.kind==="caller_assigned"&&event.occurredAt<=outcomeCutoff)assignmentAt=event.occurredAt;if(event.kind==="caller_feedback"&&(saleMilestones.length?event.occurredAt<outcomeCutoff:event.occurredAt<=outcomeCutoff)&&Array.isArray(event.metadata.questions))questions=event.metadata.questions.filter((q):q is {questionKey:string;answer:string}=>typeof q==="object"&&q!==null&&"questionKey" in q&&"answer" in q&&typeof q.questionKey==="string"&&typeof q.answer==="string");}const soldAt=saleMilestones[0]?.occurredAt??null;return {leadId:lead.id,type:lead.type,assignmentAt,facts:parseConfirmedFacts(questions),acquisition:attribution,sold:Boolean(soldAt),soldAt,saleTimestamps:saleMilestones.map(x=>x.occurredAt),financialEvents:input.financial.filter(x=>x.leadId===lead.id&&x.occurredAt<=input.asOf)};});
}
