import { describe,expect,it } from "vitest";
import { buildEconomicScore, buildMicrosegments, calibrateEvidenceSnapshots, findTwins, parseEvidenceSnapshot, type EvidenceCase } from "./domain";
import { parseConfirmedFacts } from "./facts";
const facts=parseConfirmedFacts([{questionKey:"primaryProfile",answer:"parado_desempleado"},{questionKey:"motivationAngles",answer:'["financial_stability"]'}]);
const base=(id:string,sold=false):EvidenceCase=>({leadId:id,assignmentAt:new Date("2025-01-01"),facts,acquisition:{source:"Meta",campaign:"A",ad:null,creative:null,acquisitionAngle:null},sold,financialEvents:[]});
describe("commercial evidence",()=>{
 it("rejects future asOf and keeps missing ledger truth unknown",()=>{expect(()=>buildEconomicScore({target:base("t"),cohort:[],asOf:new Date("2999-01-01"),currency:"EUR"})).toThrow();expect(buildEconomicScore({target:base("t"),cohort:Array.from({length:10},(_,i)=>base(String(i),i<5)),asOf:new Date("2026-01-01"),currency:"EUR"}).expectedMarginCents).toBeNull();});
 it("uses reversal-aware selected-currency monetary truth",()=>{const sold=base("sold",true);sold.financialEvents=[{id:"p",kind:"payment_received",amountCents:10000,currency:"EUR",reversalOfId:null,occurredAt:new Date("2025-02-01")},{id:"c",kind:"cost",amountCents:2000,currency:"EUR",reversalOfId:null,occurredAt:new Date("2025-02-01")},{id:"r",kind:"reversal",amountCents:2000,currency:"EUR",reversalOfId:"c",occurredAt:new Date("2025-02-02")}];const score=buildEconomicScore({target:base("t"),cohort:Array.from({length:10},(_,i)=>i===0?sold:base(String(i))),asOf:new Date("2026-01-01"),currency:"EUR"});expect(score.realizedMarginBeforeAdsMedianCents).toBe(10000);});
 it("deidentifies twins and selection is invariant to outcome",()=>{const first=findTwins({target:base("target"),cohort:[base("a",false),base("b",true)],asOf:new Date("2026-01-01"),currency:"EUR"});const second=findTwins({target:base("target"),cohort:[base("a",true),base("b",false)],asOf:new Date("2026-01-01"),currency:"EUR"});expect(first.map(x=>x.caseRef)).toEqual(second.map(x=>x.caseRef));expect(first[0]).not.toHaveProperty("leadId");});
 it("suppresses microsegments with small complements",()=>{const cohort=Array.from({length:35},(_,i)=>base(String(i),i<10));expect(buildMicrosegments({cohort,asOf:new Date("2026-01-01"),currency:"EUR"})).toHaveLength(0);});
 it("calibrates only mature server-shaped snapshots",()=>{const snapshot=parseEvidenceSnapshot({policyVersion:"v1",asOf:"2025-01-01",target:"sale",probabilityBps:5000,expectedMarginCents:null,currency:"EUR",fallback:"global",sample:30,confidence:"medium",features:{source:"Meta"}});expect(snapshot).not.toBeNull();expect(parseEvidenceSnapshot({...snapshot,probabilityBps:20000})).toBeNull();const result=calibrateEvidenceSnapshots({asOf:new Date("2026-02-01"),rows:[{snapshot:snapshot!,shownAt:new Date("2026-01-01"),soldAt:new Date("2026-01-10")},{snapshot:snapshot!,shownAt:new Date("2026-01-20"),soldAt:null}]});expect(result.sample).toBe(1);expect(result.brier).toBe(0.25);});
 it("excludes pre-shown sales and missing economic probabilities from calibration",()=>{const snapshot=parseEvidenceSnapshot({policyVersion:"v1",asOf:"2025-01-01",target:"sale",probabilityBps:5000,expectedMarginCents:null,currency:"EUR",fallback:"global",sample:30,confidence:"medium",features:{}})!;const missing=parseEvidenceSnapshot({policyVersion:"v1",asOf:"2025-01-01",target:"sale",probabilityBps:null,expectedMarginCents:null,currency:null,fallback:"unavailable",sample:0,confidence:"insufficient",features:{},status:"economic_truth_missing"})!;const result=calibrateEvidenceSnapshots({asOf:new Date("2026-03-01"),rows:[{snapshot,shownAt:new Date("2026-01-01"),soldAt:new Date("2025-12-31")},{snapshot:missing,shownAt:new Date("2026-01-01"),soldAt:new Date("2026-01-10")}]});expect(result.sample).toBe(1);expect(result.brier).toBe(0.25);});
});
