import { TRPCError } from "@trpc/server";
import { and, db, eq, lte } from "@crm-fran/db";
import { leadActivityEvents, leadFinancialEvents, leads } from "@crm-fran/db/schema/index";
import { buildAsOfCases } from "./cohort";
import { buildEconomicScore, buildMicrosegments, calibrateEvidenceSnapshots, findTwins, parseEvidenceSnapshot, COMMERCIAL_EVIDENCE_POLICY_VERSION, type EvidenceSnapshot } from "./domain";

async function evidenceData(asOf:Date){
 const [leadRows,activityRows,financialRows]=await Promise.all([
  db.select({id:leads.id,type:leads.type,createdAt:leads.createdAt,callerId:leads.callerId,closerId:leads.closerId,name:leads.name}).from(leads).where(lte(leads.createdAt,asOf)),
  db.select({id:leadActivityEvents.id,leadId:leadActivityEvents.leadId,kind:leadActivityEvents.kind,occurredAt:leadActivityEvents.occurredAt,description:leadActivityEvents.description,metadata:leadActivityEvents.metadata}).from(leadActivityEvents).where(lte(leadActivityEvents.occurredAt,asOf)),
  db.select({id:leadFinancialEvents.id,leadId:leadFinancialEvents.leadId,kind:leadFinancialEvents.kind,amountCents:leadFinancialEvents.amountCents,currency:leadFinancialEvents.currency,reversalOfId:leadFinancialEvents.reversalOfId,occurredAt:leadFinancialEvents.occurredAt}).from(leadFinancialEvents).where(lte(leadFinancialEvents.occurredAt,asOf)),
 ]);
 return {leadRows,cases:buildAsOfCases({leads:leadRows,activities:activityRows,financial:financialRows,asOf})};
}
export async function buildEvidenceSnapshotForLead(input:{leadId:string;asOf:Date;actionType:string}):Promise<EvidenceSnapshot>{const {cases}=await evidenceData(input.asOf);const target=cases.find(x=>x.leadId===input.leadId);const currency=target?[...new Set(target.financialEvents.map(x=>x.currency))].sort()[0]:undefined;if(!target||!currency)return {policyVersion:COMMERCIAL_EVIDENCE_POLICY_VERSION,asOf:input.asOf.toISOString(),target:"sale",probabilityBps:null,expectedMarginCents:null,currency:null,fallback:"unavailable",sample:0,confidence:"insufficient",features:{actionType:input.actionType},status:"economic_truth_missing"};const score=buildEconomicScore({target,cohort:cases,asOf:input.asOf,currency});return {policyVersion:score.policyVersion,asOf:input.asOf.toISOString(),target:"sale",probabilityBps:score.probabilityBps,expectedMarginCents:score.expectedMarginCents,currency,fallback:score.fallback,sample:score.denominator,confidence:score.confidence,features:{actionType:input.actionType,source:target.acquisition.source??"missing",profile:target.facts.primaryProfile.kind==="value"?target.facts.primaryProfile.value:"missing"}};}
export function canReadEvidenceLead(input:{actorId:string;admin:boolean;callerId:string|null;closerId:string|null}){return input.admin||input.callerId===input.actorId||input.closerId===input.actorId;}
export async function getLeadEvidence(input:{leadId:string;asOf:Date;currency:string;actorId:string;admin:boolean}){const {leadRows,cases}=await evidenceData(input.asOf);const lead=leadRows.find(x=>x.id===input.leadId);if(!lead)throw new TRPCError({code:"NOT_FOUND",message:"Lead not found"});if(!canReadEvidenceLead({...input,callerId:lead.callerId,closerId:lead.closerId}))throw new TRPCError({code:"FORBIDDEN",message:"Lead is not assigned to this user"});const target=cases.find(x=>x.leadId===input.leadId)!;return {lead:{id:lead.id,name:lead.name},score:buildEconomicScore({target,cohort:cases,asOf:input.asOf,currency:input.currency}),twins:findTwins({target,cohort:cases,asOf:input.asOf,currency:input.currency,admin:input.admin})};}
export async function listEvidenceCurrencies(input:{actorId:string;admin:boolean}){const [owners,events]=await Promise.all([db.select({id:leads.id,callerId:leads.callerId,closerId:leads.closerId}).from(leads),db.select({leadId:leadFinancialEvents.leadId,currency:leadFinancialEvents.currency}).from(leadFinancialEvents)]);const allowed=new Set(owners.filter(x=>input.admin||x.callerId===input.actorId||x.closerId===input.actorId).map(x=>x.id));return [...new Set(events.filter(x=>allowed.has(x.leadId)).map(x=>x.currency))].sort();}
export async function listEvidenceLeads(input:{actorId:string;admin:boolean;query?:string}){const rows=await db.select({id:leads.id,name:leads.name,callerId:leads.callerId,closerId:leads.closerId}).from(leads);const q=input.query?.trim().toLowerCase();return rows.filter(x=>(input.admin||x.callerId===input.actorId||x.closerId===input.actorId)&&(!q||x.name.toLowerCase().includes(q))).slice(0,50).map(({id,name})=>({id,name}));}
export async function getMicrosegments(asOf:Date,currency:string){const {cases}=await evidenceData(asOf);return buildMicrosegments({cohort:cases,asOf,currency});}
export async function getConfidenceCentre(asOf:Date){const {leadRows,cases}=await evidenceData(asOf);const shown=await db.select({id:leadActivityEvents.id,leadId:leadActivityEvents.leadId,occurredAt:leadActivityEvents.occurredAt,metadata:leadActivityEvents.metadata}).from(leadActivityEvents).where(and(lte(leadActivityEvents.occurredAt,asOf),eq(leadActivityEvents.kind,"recommendation_shown")));const parsed=shown.flatMap(x=>{const snapshot=parseEvidenceSnapshot(x.metadata.evidenceSnapshot);if(!snapshot)return[];return[{snapshot,shownAt:x.occurredAt,soldAt:cases.find(c=>c.leadId===x.leadId)?.saleTimestamps?.find(saleAt=>saleAt>=x.occurredAt)??null}]});const calibration=calibrateEvidenceSnapshots({rows:parsed,asOf});return {policyVersion:"commercial-evidence-v1",coverage:{eligible:leadRows.length,calibrated:calibration.sample},legacyExcluded:shown.length-parsed.length,brier:calibration.brier,ece:calibration.ece,bins:calibration.bins,suggestedChanges:[],mode:"shadow-only" as const};}
